- theme: Carbon Emissions
  indicators:
    - name: Annual Carbon Emissions
      key: annual_carbon_emissions
      unit: tonnes CO₂
      expected_type: float
      aim: reduction
      has_target: true
      aliases:
        - Carbon Footprint
        - Total GHG Emissions
        - Scope 1 and 2 Emissions
        - CO₂ Emissions
        - Greenhouse Gas Emissions
        - GHG Output
        - Total Emissions
        - Emissions from Operations
        - Emissions Indexed to Sales
        - Operational Emissions
        - GHG Emissions (Scope 1+2)
        - Company-Wide Carbon Output
      validation:
        min: 0
        max: 100000000
        warn_above: 50000000

- theme: Water Consumption
  indicators:
    - name: Annual Water Consumption
      key: annual_water_use
      unit: cubic meters
      expected_type: float
      aim: reduction
      has_target: true
      aliases:
        - Total Water Use
        - Water Withdrawn
        - Water Usage
        - Water Consumption
        - Water Utilization
        - Water Footprint
        - Water Draw
        - Water Intake
        - Corporate Water Use
        - Freshwater Use
        - Industrial Water Use
        - Total Water Withdrawal
        - Volume of Water Used
        - Annual Water Withdrawal
        - Water withdrawal
      validation:
        min: 0
        max: 100000000
        warn_above: 50000000

- theme: Renewable Energy
  indicators:
    - name: Renewable Energy Usage
      key: renewable_energy_use
      unit: MWh
      expected_type: float
      aim: increase
      has_target: true
      aliases:
        - Renewable Energy Usage
        - Renewable Electricity Usage
        - Renewable Energy Consumed
        - Renewable Energy Consumption
        - Renewable Power Consumption
        - Renewable Electricity Consumed
        - Total Renewable Energy Use
        - Renewable Energy Demand
        - Renewable Electricity Demand
        - Renewable Energy Utilization
        - Total Renewable Energy (MWh)
        - Total Renewable Power Used
        - Renewable Electricity Utilized
        - Renewable Electricity (MWh)
        - Renewable Power Generated On-Site
        - Renewable Energy from Grid
        - Clean Electricity Usage
        - Green Power Consumption
        - Green Energy Usage
        - Green Electricity Consumed
        - Green Energy Load
      validation:
        min: 0
        max: 10000000
        warn_above: 5000000

- theme: Materials Usage
  indicators:
    - name: Sustainable Materials Usage Ratio
      key: sustainable_materials_ratio
      unit: percent
      expected_type: float
      aim: increase
      has_target: false
      aliases:
        - Sustainable Materials Percentage
        - "% Sustainable Materials"
        - Sustainable Content Ratio
        - Recycled Content Percentage
        - "% Recycled Materials"
        - Bio-based Materials Percentage
        - Sustainable Input Ratio
        - Eco-friendly Materials Proportion
        - Green Materials Percentage
        - Circular Materials Rate
        - Renewable Materials Percentage
        - Proportion of Sustainable Materials
        - Sustainable Sourcing Ratio
        - Environmentally Preferred Materials %
        - Low-impact Materials Percentage
        - Certified Sustainable Materials %
      validation:
        min: 0
        max: 100
        warn_above: 95

- theme: Waste Management
  indicators:
    - name: Waste Recycling Rate
      key: waste_recycling_rate
      unit: percent
      expected_type: float
      aim: increase
      has_target: false
      aliases:
        - Landfill Diversion Rate
        - Recycling Rate
        - "% Waste Recycled"
        - Waste Recovery Rate
        - Zero Waste to Landfill
        - Reuse/Recycling Rate
        - Recycled Waste Proportion
        - Recyclables Collected
        - Solid Waste Recovery Rate
        - "% of Waste Diverted"
        - "% Waste Recovery"
        - Recycling Performance
        - Waste Diversion Rate
        - Recycling Effectiveness
      validation:
        min: 0
        max: 100
        warn_above: 95