[tool.poetry]
version = "0.1.0"
name = "coursework-one"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
sphinx = "^7.1.2"
sphinx-rtd-theme = "^1.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"