version: '3.5'

services:
    # ✅ MongoDB
    mongo_db:
      container_name: mongo_db_cw
      image: mongo:latest
      ports:
        - 27019:27017

    # ✅ PostgreSQL
    postgres_db:
        container_name: postgres_db_cw
        image: postgres:10.5        
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - PGUSER=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5439:5432'  
        volumes:
          - postgres-data:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "pg_isready"]
          interval: 10s
          timeout: 5s
          retries: 5          

    # ✅ PostgreSQL Seed 
    postgres_seed:
      container_name: postgres_seed_cw
      restart: on-failure
      environment:
        POSTGRES_DATABASE: postgres_feeder
        POSTGRES_HOST: postgres_feeder
        POSTGRES_PORT: 5439
        POSTGRES_USER: postgres_feeder
        POSTGRES_PASSWORD: postgres_feeder
      depends_on:
        postgres_db:
          condition: service_healthy
      build: 
        dockerfile: ./000.Database/SQL/Dockerfile

    # ✅ pgAdmin (PostgreSQL GUI)
    pgadmin:
      container_name: pg_admin_cw
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5051:80"

    # ✅ MinIO
    miniocw:
      image: minio/minio
      container_name: miniocw
      networks:
        - iceberg_net  
      environment:
        - MINIO_ROOT_USER=ift_bigdata
        - MINIO_ROOT_PASSWORD=minio_password
        - MINIO_DOMAIN=miniocw
      ports:
        - 9001:9001
        - 9000:9000
      command: ["server", "/data", "--console-address", ":9001"]

    # ✅ MinIO Client
    minio_client_cw:
      container_name: minio_client_cw
      networks:
        - iceberg_net  
      depends_on:
        - miniocw
      image: minio/mc
      environment:
        - AWS_ACCESS_KEY_ID=ift_bigdata
        - AWS_SECRET_ACCESS_KEY=minio_password
        - AWS_REGION=us-east-1
      entrypoint: >
        /bin/bash -c "
        until (/usr/bin/mc config host add minio http://miniocw:9000 ift_bigdata minio_password) do echo '...waiting...' && sleep 1; done;
        sleep 10 && /usr/bin/mc rm -r --force minio/csreport;
        sleep 10 && /usr/bin/mc mb minio/csreport;
        mc anonymous set public minio/csreport;
        tail -f /dev/null
        "

    # ✅ Zookeeper
    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      container_name: zookeeper_cw
      restart: always
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181

    # ✅ Kafka
    kafka:
      image: confluentinc/cp-kafka:latest
      container_name: kafka_cw
      restart: always
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      depends_on:
        - zookeeper

    # ✅ Scraper (Newly Added)
    scraper:
      container_name: scraper_cw
      build: .
      networks:
        - iceberg_net
      depends_on:
        - mongo_db
        - miniocw
        - postgres_db
      environment:
        - MONGO_URI=mongodb://mongo_db:27017
        - MINIO_HOST=miniocw
        - POSTGRES_HOST=postgres_db
      command: python csr_scraper.py  # Runs the scraper with scheduler

volumes:
  postgres-data:

networks:
  iceberg_net:
