repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        files: ^(pipeline[1-4]/|scheduler\.py|config/)
    -   id: end-of-file-fixer
        files: ^(pipeline[1-4]/|scheduler\.py|config/)
    -   id: check-yaml
        files: ^(pipeline[1-4]/|scheduler\.py|config/)
    -   id: check-added-large-files
        files: ^(pipeline[1-4]/|scheduler\.py|config/)

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        types: [python]
        files: ^(pipeline[1-4]/|scheduler\.py|config/)

-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        types: [python]
        files: ^(pipeline[1-4]/|scheduler\.py|config/)

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        types: [python]
        files: ^(pipeline[1-4]/|scheduler\.py|config/) 