pipelines:
  pipeline1:
    name: "PDF Download Pipeline"
    enabled: true
    cron: "0 0 * * *"  # 每天午夜运行
    description: "Downloads PDF reports from sources"
    
  pipeline2:
    name: "Text Extraction Pipeline"
    enabled: true
    cron: "30 0 * * *"  # 每天午夜00:30运行
    description: "Extracts text from downloaded PDFs"
    
  pipeline3:
    name: "ESG Metrics Pipeline"
    enabled: true
    cron: "0 1 * * *"  # 每天凌晨1点运行
    description: "Extracts ESG metrics and writes to database"
    
  pipeline4:
    name: "Dashboard Pipeline"
    enabled: true
    cron: "30 1 * * *"  # 每天凌晨1:30运行
    description: "Updates the visualization dashboard" 