database:
  host: localhost
  port: 5439
  name: fift
  user: postgres
  password: postgres
  schema: csr_reporting

test_data:
  sample_pdf: "tests/test_data/sample.pdf"
  
pipelines:
  pipeline1:
    enabled: true
    test_url: "https://example.com/test.pdf"
    
  pipeline2:
    enabled: true
    min_text_length: 100
    
  pipeline3:
    enabled: true
    tables:
      - esg_indicators
      - data_lineage
    
  pipeline4:
    enabled: true
    metrics:
      - scope1_emissions
      - scope2_emissions
      - total_energy_consumption 