version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_TYPE=backend
      - MONGODB_URI=mongodb://mongo_db_cw:27017
    ports:
      - "8081:8081"
    networks:
      - app_network
      - default
    depends_on:
      - mongo_db_cw

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_TYPE=frontend
      - BACKEND_URL=http://backend:8081
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    name: app_network
  default:
    external: true
    name: team_adansonia_2_default  # This should match your outer docker-compose network name 