# Generated by Django 4.2.9 on 2025-01-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirPollution",
            fields=[
                ("ISIN", models.CharField(max_length=12)),
                ("CompanyName", models.CharField(max_length=200)),
                ("Country", models.CharField(max_length=100)),
                ("Industry", models.CharField(max_length=100)),
                (
                    "Ticker",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirPollutionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dates", models.DateField()),
                ("GHG_SCOPE_1", models.FloatField()),
                ("GHG_SCOPE_2_LOCATION_BASED", models.FloatField()),
                ("GHG_SCOPE_2_MARKET_BASED", models.FloatField()),
                ("CO2_SCOPE_1", models.FloatField()),
                ("CO2_SCOPE_2_LOCATION_BASED", models.FloatField()),
                ("CO2_SCOPE_2_MARKET_BASED", models.FloatField()),
                ("SCOPE_2_GHG_CO2_EMISSIONS", models.FloatField()),
                ("SCOPE_1_GHG_CO2_EMISSIONS", models.FloatField()),
                (
                    "airPollution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticker",
                        to="theme_pixel.airpollution",
                    ),
                ),
            ],
        ),
    ]
