# Generated by Django 4.2.9 on 2025-01-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theme_pixel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airpollutiondata",
            name="CO2_SCOPE_1",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="airpollutiondata",
            name="CO2_SCOPE_2_LOCATION_BASED",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="airpollutiondata",
            name="CO2_SCOPE_2_MARKET_BASED",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="airpollutiondata",
            name="GHG_SCOPE_1",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="airpollutiondata",
            name="GHG_SCOPE_2_LOCATION_BASED",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="airpollutiondata",
            name="GHG_SCOPE_2_MARKET_BASED",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="airpollutiondata",
            name="SCOPE_1_GHG_CO2_EMISSIONS",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="airpollutiondata",
            name="SCOPE_2_GHG_CO2_EMISSIONS",
            field=models.FloatField(null=True),
        ),
    ]
