# Generated by Django 3.2.13 on 2025-05-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theme_pixel", "0002_alter_airpollutiondata_co2_scope_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyReportData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(max_length=10)),
                ("security", models.CharField(max_length=200)),
                (
                    "gics_sector",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gics_industry",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("report_url", models.URLField(blank=True, max_length=500, null=True)),
                ("report_year", models.IntegerField(blank=True, null=True)),
                ("annual_carbon_emissions", models.FloatField(blank=True, null=True)),
                ("annual_water_consumption", models.FloatField(blank=True, null=True)),
                ("renewable_energy_usage", models.FloatField(blank=True, null=True)),
                (
                    "sustainable_materials_usage_ratio",
                    models.FloatField(blank=True, null=True),
                ),
                ("waste_recycling_rate", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Company Report Data",
                "verbose_name_plural": "Company Report Data",
            },
        ),
    ]
