# Generated by Django 3.2.13 on 2025-05-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theme_pixel", "0003_companyreportdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyReport",
            fields=[
                ("symbol", models.CharField(max_length=10)),
                (
                    "security",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                (
                    "gics_sector",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gics_industry",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Company Report",
                "verbose_name_plural": "Company Reports",
            },
        ),
    ]
