version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: fift_postgres
    environment:
      POSTGRES_DB: fift
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  minio:
    image: minio/minio
    container_name: minio
    networks:
      iceberg_net:
    environment:
      - MINIO_ROOT_USER=ift_bigdata
      - MINIO_ROOT_PASSWORD=minio_password
      - MINIO_DOMAIN=minio
    ports:
      - 9001:9001
      - 9000:9000
    command: [ "server", "/data", "--console-address", ":9001" ]


  minio_client:
      container_name: minio_client
      networks:
        iceberg_net:
      depends_on:
        - minio
      image: minio/mc
      environment:
        - AWS_ACCESS_KEY_ID=ift_bigdata
        - AWS_SECRET_ACCESS_KEY=minio_password
        - AWS_REGION=us-east-1
      entrypoint: >
        /bin/bash -c "
        until (/usr/bin/mc config host add minio http://minio:9000 ift_bigdata minio_password) do echo '...waiting...' && sleep 1; done;
        sleep 10 && /usr/bin/mc rm -r --force minio/csr-reports;
        sleep 10 && /usr/bin/mc mb minio/csr-reports;
        mc anonymous set public minio/csr-reports;
        tail -f /dev/null
        "

volumes:
  pgdata:
  minio-data:


networks:
  iceberg_net:
    driver: bridge