# coursework_two/config/conf.yaml
# ───────────────────────────────────────────────────────────────────────────
# CSR 数据抽取 & 存储 配置文件（中英双语注释）
# Configuration for CSR data extraction & storage
# ───────────────────────────────────────────────────────────────────────────

# ── PDF 来源 / PDF source ────────────────────────────────────────────────
pdf_path:          "/path/to/local/report.pdf"          # 本地测试用 PDF 路径 / local fallback PDF path
pdf_object_key:    "reports/2024_NVIDIA.pdf"            # MinIO 对象键 / MinIO object key

# ── 输出目录 & 文件名 / output directory & filenames ─────────────────────
output_dir:        "output"                             # 所有输出（PDF/md/json/csv）放在此文件夹下
output_pdf:        "filtered_report_pages.pdf"          # 过滤后 PDF 文件名
output_md:         "filtered_report_parsed.md"          # 解析后 Markdown 文件名
output_json:       "extracted_data.json"                # 第一轮原始 JSON
final_json:        "final_standardized.json"            # 第二轮标准化 JSON
output_csv:        "standardized_data.csv"              # 扁平化 CSV

# ── Groq LLM 设置 / Groq LLM settings ────────────────────────────────────
groq_api_key:      ""                                   # 如果已用环境变量 G﻿ROQ_API_KEY，请留空
groq_base_url:     "https://api.groq.com/openai/v1"
groq_model:        "meta-llama/llama-4-scout-17b-16e-instruct"

# ── Docling 分页标记 / Docling page-break marker ─────────────────────────
page_break:        "---TEMP_DOCLING_PAGE_BREAK_SPECIAL---"

# ── MinIO 存储配置 / MinIO settings ──────────────────────────────────────
minio:
  endpoint:        "localhost:9000"                       # Compose 中的 MinIO 服务名与端口
  access_key:      "ift_bigdata"
  secret_key:      "minio_password"
  bucket:          "csr-reports"
  secure:          false                                # http=false / https=true

# ── Database settings (MongoDB & PostgreSQL) ─────────────────────────────
database:
  mongo_uri:       "mongodb://localhost:27019"           # Docker 映射 27019 -> 容器 27017
  mongo_db:        "csr_extraction"                      # MongoDB 数据库名
  postgres_uri:    "postgresql://postgres:postgres@localhost:5439/fift"
  postgres_schema: "csr_reporting"

# ── 自定义年份正则 / custom year regex (optional) ────────────────────────
year_pattern:      "\\b(?:FY|FISCAL\\s*YEAR)?\\s*(?:20\\d{2}|['‘’]?\\d{2})\\b"

# ── 可持续主题提取规则 / sustainability themes ────────────────────────────
themes:
  "GHG Emissions":
    unit: "\\b(?:tco2e|mtco2e|ktco2e)\\b"
    keywords:
      - "\\b(scope\\s*1|scope\\s*one)\\b"
      - "\\b(scope\\s*2|scope\\s*two)\\b"
      - "\\b(ghg|greenhouse gas|emissions)\\b"
    require_multiple_year_occurrences: true
    min_keyword_hits: 2

  "Energy":
    unit: "\\b(?:MWh|GWh|kWh)\\b"
    keywords:
      - "\\benergy consumption\\b"
      - "\\brenewable energy\\b"
    require_multiple_year_occurrences: true
    min_keyword_hits: 2

  "Water":
    unit: "\\b(?:ML|m³|gallons?)\\b"
    keywords:
      - "\\bwater (?:withdrawal|consumption)\\b"
    require_multiple_year_occurrences: true
    min_keyword_hits: 1

  "Operational Waste":
    unit: "\\b(?:tonnes?|kg|lbs)\\b"
    keywords:
      - "\\b(waste|waste management|solid waste|hazardous waste)\\b"
      - "\\b(disposal|recycling|landfill)\\b"
    require_multiple_year_occurrences: true
    min_keyword_hits: 2

  "Product Sustainability & Circularity":
    unit: "\\b(?:%|percent)\\b"
    keywords:
      - "\\b(circularity|circular economy|product sustainability)\\b"
      - "\\b(recycl|upcycl|remanufactur)\\b"
    require_multiple_year_occurrences: false
    min_keyword_hits: 1

  "Social":
    unit: ""                                            # 社会主题无量化单位，留空或自定义
    keywords:
      - "\\b(employee (?:health|safety|diversity))\\b"
      - "\\b(community engagement|social responsibility)\\b"
      - "\\b(labor standards|human rights)\\b"
    require_multiple_year_occurrences: false
    min_keyword_hits: 1

  "Governance":
    unit: ""                                            # 治理主题无量化单位，留空
    keywords:
      - "\\b(corporate governance|board composition)\\b"
      - "\\b(ethics|compliance|anti-corruption)\\b"
      - "\\b(risk management)\\b"
    require_multiple_year_occurrences: false
    min_keyword_hits: 1
